### ISSUE TITLE
[BUG] Moving to the left is more sensitive to lean than moving to the right

### ISSUE THREAD

**Issue by SrMoroxide** [IgnoredSoul/LethalSex#2]
https://github.com/IgnoredSoul/LethalSex/assets/152836693/c68a10d9-201d-4155-bd4c-d4655aa7b8c6

**Comment by IgnoredSoul** [comment]
Thank you for the bug report.

With the upcoming fix release, this should hopefully fix this issue. If the problem persist please let me know.
I will leave this open since the patch is not released yet!

**Comment by IgnoredSoul** [comment]
[v1.3.1](https://github.com/IgnoredSoul/LethalSex/blob/main/LethalSanity/README.md) has resolved this issue. Thank you :3
